name: Deploy WAR file to Ubuntu Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

     # Upload src code
    - name: Deploy src code to Ubuntu server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ResidentManagement/src/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/projects/ResidentManagement/src/

    # Upload the web file
    - name: Deploy web element to Ubuntu server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ResidentManagement/web/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/ubuntu/projects/ResidentManagement/web/
        
    # Build the WAR file
    - name: Build WAR on Ubuntu server
      run: |
        ssh -o StrictHostKeyChecking=no -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/ubuntu/projects/ResidentManagement/
        ant clean build-war
        EOF

    - name: Deploy WAR to Tomcat
      run: |
        ssh -o StrictHostKeyChecking=no -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cp /home/ubuntu/projects/ResidentManagement/dist/ResidentManagement.war /home/ubuntu/apache-tomcat-10.1.34/webapps/
        EOF
        
